### PR TITLE
updating knexfile's location for veritable-ui chart.

### PR DESCRIPTION
**Pull request by n3op2**
# Pull Request

## Checklist
- [x] Have you read Digital Catapult's [Code of Conduct](https://github.com/digicatapult/.github/blob/main/CODE_OF_CONDUCT.md)?
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## PR Type

Please delete options that are irrelevant.

- [x] Feature

## Linked tickets

https://digicatapult.atlassian.net/browse/VR-99 - Jira

## High level description

Changing knexfile's location as we have moved away from commonJS to esm

## Detailed description

Not much to add here, updating helm config along with README

### CODE REVIEW

**Review by dblane-digicatapult — APPROVED** [review]

**Review by dblane-digicatapult — CHANGES_REQUESTED** [review]
Wrong directory

**Review by dblane-digicatapult — CHANGES_REQUESTED** [review]
Swagger jaon isn't being included in the container

**Comment by mattdean-digicatapult** [comment]
My guess is this is a typescript config thing. Need to make sure typescript includes the json file in it's src list

**Review by dblane-digicatapult — APPROVED** [review]
Please create a bug ticket to alter the descriptions in `values.yaml` to change descriptions from being `sqnc`

**Pull request merged**
